### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Ghostlyr** [Ghostlyr/LogisticsPipes#1]
That's what I found, what should to do:
- [ ] Change "page" strings to global localizable names
- [ ] Localize in LogisticsBrokenItem tooltips: "This is an useless item" and "You get this by trying to" strings
- [ ] Localize in LogisticsItemCard "This is no valid Card" string
